stages:
  data_ingestion:
    cmd: python src/salesPrediction/pipeline/s01_data_ingestion.py
    deps:
      - src/salesPrediction/pipeline/s01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion

  data_validation:
    cmd: python src/salesPrediction/pipeline/s02_data_validation.py
    deps:
      - src/salesPrediction/pipeline/s02_data_validation.py
      - artifacts/data_ingestion/raw/Train.csv
      - configs/config.yaml
      - configs/schema.yaml
    outs:
      - artifacts/data_validation
    # metrics:
    #   - artifacts/data_validation/report.json:
    #       cache: false

  data_preprocessing:
    cmd: python src/salesPrediction/pipeline/s03_data_preprocessing.py
    deps:
      - src/salesPrediction/pipeline/s03_data_preprocessing.py
      - artifacts/data_ingestion/raw/Train.csv
      - configs/config.yaml
      - configs/schema.yaml
    outs:
      - artifacts/data_preprocessing/Train_preprocessed.npy
      - artifacts/data_preprocessing/preprocessed.pkl
